# 基础配置
baseURL = "https://<empty-space-miao>.github.io/"
theme = "PaperMod"
# 开启 paginate 功能，否则首页可能不显示文章列表


# 将中文设置为默认语言
defaultContentLanguage = "zh"

# 多语言配置块
[languages]
  # 中文配置 (新的繁體中文版)
[languages.zh]
  languageName = "繁體中文"
  languageCode = "zh-tw"  # 標準繁體中文代碼
  weight = 1
  title = "回音收集員" # 您的網站標題（可自行修改）
  [languages.zh.params]
    description = "一個關於奇點理論與密碼學的博客" # 您的網站描述（可自行修改）
  [languages.zh.menu]
    [[languages.zh.menu.main]]
      identifier = "archives"
      name = "歸檔"
      url = "/archives/"
      weight = 10
    [[languages.zh.menu.main]]
      identifier = "tags"
      name = "標籤"
      url = "/tags/"
      weight = 20
  # 英文配置
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2 # 权重
    title = "The Echo Collector" # 英文网站的标题
    [languages.en.params]
      description = "A blog about Singularity Theory and Cryptography"
    [languages.en.menu] # 英文网站的菜单
      [[languages.en.menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives/"
        weight = 10
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20
# 新的、正确的写法
[pagination]
  pagerSize = 5
# ==================================
# hugo.toml 文件末尾
# ==================================

# 添加这个 [params] 配置块来启用数学公式支持
[params]
  [params.math]
    enable = true # 开启数学公式渲染 (使用 KaTeX)

# 这是一个用于触发部署的测试提交