# 工作流名称
name: Deploy Hugo site to Pages

# 触发条件：当推送到 main 分支时触发
on:
  push:
    branches:
      - main
  workflow_dispatch:

# 权限设置：允许 Actions 写入 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 并发设置：确保每次只有一个部署任务在运行
concurrency:
  group: "pages"
  cancel-in-progress: false

# 默认设置
defaults:
  run:
    shell: bash

# 任务定义
jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.149.0/hugo_extended_0.149.0_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
